### PR TITLE
fix: incorrect check for existing socket clients

### LINKED ISSUE #61: Browser keeps refreshing with multiple entry points/configurations
* Operating System: Windows 7
* Node Version: 6.10
* NPM Version: 5.3.0
* webpack Version: 4.6.0
* webpack-serve Version: 1.0.2

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

### Code
This the `webpack-serve` API code.

```js
const config = require('webpack.config')
serve({
 config,
 logLevel: 'trace',
 dev: {
   publichPath: '/'
 },
 add: (app, middleware) => {
   middleware.webpack();
   middleware.content({
      index: 'index.html'
   });
 }
});
```

##### webpack.config.js

```js
module.exports = [
  {
     entry: {
       index: [path.resolve(__dirname, 'app.js')],
     },
     mode: 'development',
     output: {
       filename: 'output.js',
     }
  }
  {
     entry: {
       index: [path.resolve(__dirname, 'iframe-app.js')],
     },
     mode: 'development',
     output: {
       filename: 'iframe-bundle.js',
     }
  }
]
```

```html
<!-- index.html from where I serve my bundles -->

<html>
  <body>
      <iframe src="http://localhost:8080/iframe.html">

      </iframe>
     <script src="output.js"></script>
  </body>
</html>
```

```html
<!-- iframe.html where I load the second bundle -->

  <div>
     <script src="iframe-bundle.js"></script>
  </div>
```

### Expected Behavior

It should serve both bundles without refreshing the whole web page.

### Actual Behavior

The browsers keeps refreshing every time the iframe gets rendered and loads the second output.

### How Do We Reproduce?

I managed to have the same 'refreshing loop' by having two entry points that are loaded in the same page or by recreating a situation like mine (which could take longer).

### PR DESCRIPTION
**Pull request by noppa**
This PR contains a:

- [x] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

Fixes #61. 

### Breaking Changes

Shouldn't break anything, all tests still pass.

### Additional Info
Here's a repo where the issue & the fix can be tested easily: [noppa/webpack-hot-client-refresh-issue-sscce](https://github.com/noppa/webpack-hot-client-refresh-issue-sscce).

I also have the same fix for version 3, here: 91cac08bc.
Not sure how or if that should be merged, but it's there if you want to patch v3.

### CODE REVIEW

File: lib/socket-server.js [hunk 1]
```diff
@@ -61,7 +61,7 @@ function onConnection(server, options) {
 
     // only send stats to newly connected clients, if no previous clients have
     // connected and stats has been modified by webpack
-    if (options.stats && options.stats.toJson && !server.clients.length) {
+    if (options.stats && options.stats.toJson && server.clients.size === 1) {
```
Comment (shellscape) [inline lib/socket-server.js]: Is this due to `clients` being a `Set` rather than an `Array`?

Comment (noppa) [reply lib/socket-server.js]: Yep, the change from `length` to `size` is. 

Now it also expects there to be 1 connected client, instead of 0 like before, since this happens inside "connected" event callback and the new client whose connection caused that event will already be in the Set.

Comment (shellscape) [reply lib/socket-server.js]: OK, that makes sense.

**Comment by noppa** [comment]
Would it be possible to get the fix to version 3 too, as a 3.0.1 patch maybe?  
We are currently stuck with that version because of  [webpack-serve](https://github.com/webpack-contrib/webpack-serve).

**Comment by shellscape** [comment]
We don't make a habit of back-porting fixes. When a new major release comes out, that's what we support moving forward. You'll have to be patient and await an update to `webpack-serve`.

**Comment by noppa** [comment]
OK, thanks for the prompt response.

**Comment by shellscape** [comment]
No worries. Rest assured that `webpack-server` is getting love and will be updated.

**Comment by ematipico** [comment]
Thank you @noppa for your fix and @shellscape for the collaboration!
